export const types = {
    SET_LAYERS: "SET_LAYERS",
    SET_ACTIVE_LAYER: "SET_ACTIVE_LAYER",
    SET_SCATTER_PLOT_DATA: "SET_SCATTER_PLOT_LAYER",
    SET_GEO_JSON_DATA: "SET_GEO_JSON_LAYER",
    SET_LAYER_LOADING: "SET_LAYER_LOADING",
    SET_DATA_LOADING: "SET_DATA_LOADING",
    SET_ACTIVE_VISUALIZATION: "SET_ACTIVE_VISUALIZATION",
    SET_POPUP_DATA: "SET_POPUP_DATA"
};